# Generated by Django 5.0.6 on 2024-06-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_send_to_conversationmessage_sent_to_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversationmessage',
            old_name='sent_to_id',
            new_name='sent_to',
        ),
    ]
